modLoader = "javafml"
loaderVersion = "[10,)"
issueTrackerURL = "https://github.com/downloadableduck/scalable"
license = "MIT"

[[mods]]
modId = "scalable"
version = "${version}"
displayName = "Scalable"
authors = "downloadableduck"
description = '''
Resize each element of the GUI individually.
'''
logoFile = "assets/scalable/icon.png"


[modproperties.scalable]
"sodium:config_api_user" = "com.jeff.scalable.ScalableSodiumPage"


[[dependencies.scalable]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.scalable]]
modId = "minecraft"
type = "required"
versionRange = "[26.2, 26.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scalable]]
modId = "sodium"
type = "required"
versionRange = "[0.8.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scalable]]
modId = "cloth_config"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "scalable.mixins.json"
